import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const hoursAgo = (h: number) => new Date(Date.now() - h * 3_600_000);
const day = (iso: string) => new Date(`${iso}T00:00:00.000Z`);

const seed = [
  {
    handle: "alex-mercer",
    name: "Alex Mercer",
    oneLine: "Ships production Next.js apps in two-week sprints.",
    link: "alexmercer.dev",
    linkKey: "alexmercer.dev",
    iconUrl: null,
    contactEmail: "alex@alexmercer.dev",
    categorySlug: "react-next",
    availableFrom: day("2026-08-20"),
    capacity: "4-5",
    lastValue: 26,
    lastPaidAt: hoursAgo(11),
  },
  {
    handle: "studio-vernet",
    name: "Studio Vernet",
    oneLine: "Webflow builds for B2B SaaS. Design and dev in one pass.",
    link: "studiovernet.com",
    linkKey: "studiovernet.com",
    iconUrl: null,
    contactEmail: "hi@studiovernet.com",
    categorySlug: "webflow",
    availableFrom: day("2026-09-02"),
    capacity: "2-3",
    lastValue: 14,
    lastPaidAt: hoursAgo(9),
  },
  {
    handle: "nadia-roche",
    name: "Nadia Roche",
    oneLine: "Technical SEO audits and migrations. Ex-Algolia.",
    link: "nadia.roche.work",
    linkKey: "nadia.roche.work",
    iconUrl: null,
    contactEmail: "nadia@roche.work",
    categorySlug: "technical-seo",
    availableFrom: day("2026-08-01"),
    capacity: "1",
    lastValue: 12,
    lastPaidAt: hoursAgo(26),
  },
  {
    handle: "tobias-lund",
    name: "Tobias Lund",
    oneLine: "Framer sites for launch weeks. Turnaround under 5 days.",
    link: "lund.work",
    linkKey: "lund.work",
    iconUrl: null,
    contactEmail: "tobias@lund.work",
    categorySlug: "framer",
    availableFrom: day("2026-08-20"),
    capacity: "4-5",
    lastValue: 9,
    lastPaidAt: hoursAgo(20),
  },
  {
    handle: "priya-anand",
    name: "Priya Anand",
    oneLine: "LLM agent pipelines, evals, and the boring glue between.",
    link: "priya.anand.dev",
    linkKey: "priya.anand.dev",
    iconUrl: null,
    contactEmail: "priya@anand.dev",
    categorySlug: "ai-agents",
    availableFrom: day("2026-09-15"),
    capacity: "2-3",
    lastValue: 15,
    lastPaidAt: hoursAgo(62),
  },
  {
    handle: "marc-oyelaran",
    name: "Marc Oyelaran",
    oneLine: "React and TypeScript. Takes over half-finished codebases.",
    link: "oyelaran.dev",
    linkKey: "oyelaran.dev",
    iconUrl: null,
    contactEmail: "marc@oyelaran.dev",
    categorySlug: "react-next",
    availableFrom: day("2026-08-10"),
    capacity: "4-5",
    lastValue: 6,
    lastPaidAt: hoursAgo(38),
  },
  {
    handle: "jo-bergstrom",
    name: "Jo Bergström",
    oneLine: "Brand identity for small software companies.",
    link: "bergstrom.studio",
    linkKey: "bergstrom.studio",
    iconUrl: null,
    contactEmail: "jo@bergstrom.studio",
    categorySlug: "brand-identity",
    availableFrom: day("2026-08-18"),
    capacity: "2-3",
    lastValue: 5,
    lastPaidAt: hoursAgo(74),
  },
  {
    handle: "kit-vasquez",
    name: "Kit Vasquez",
    oneLine: "Shopify themes and headless storefronts.",
    link: "kitvasquez.com",
    linkKey: "kitvasquez.com",
    iconUrl: null,
    contactEmail: "kit@kitvasquez.com",
    categorySlug: "shopify",
    availableFrom: day("2026-09-08"),
    capacity: "1",
    lastValue: 4,
    lastPaidAt: hoursAgo(96),
  },
  {
    handle: "sam-aldridge",
    name: "Sam Aldridge",
    oneLine: "Product video and launch edits for SaaS teams.",
    link: "samaldridge.co",
    linkKey: "samaldridge.co",
    iconUrl: null,
    contactEmail: "sam@samaldridge.co",
    categorySlug: "video-motion",
    availableFrom: day("2026-08-20"),
    capacity: "2-3",
    lastValue: 0.42,
    lastPaidAt: hoursAgo(320),
  },
  {
    handle: "renata-silva",
    name: "Renata Silva",
    oneLine: "Launch copy and product pages for B2B tools.",
    link: "renatasilva.me",
    linkKey: "renatasilva.me",
    iconUrl: null,
    contactEmail: "renata@renatasilva.me",
    categorySlug: "copywriting",
    availableFrom: day("2026-08-20"),
    capacity: "2-3",
    lastValue: 0.3,
    lastPaidAt: hoursAgo(400),
  },
  {
    handle: "hugo-ferreira",
    name: "Hugo Ferreira",
    oneLine: "Native iOS, Swift, and the App Store grind.",
    link: "hugoferreira.app",
    linkKey: "hugoferreira.app",
    iconUrl: null,
    contactEmail: "hugo@ferreira.app",
    categorySlug: "ios-android",
    availableFrom: day("2026-09-22"),
    capacity: "4-5",
    lastValue: 0.2,
    lastPaidAt: hoursAgo(500),
  },
  {
    handle: "dana-whitlock",
    name: "Dana Whitlock",
    oneLine: "dbt, Snowflake, and the pipelines nobody wants to own.",
    link: "danawhitlock.dev",
    linkKey: "danawhitlock.dev",
    iconUrl: null,
    contactEmail: "dana@danawhitlock.dev",
    categorySlug: "data-engineering",
    availableFrom: day("2026-08-20"),
    capacity: "2-3",
    lastValue: 0.004,
    lastPaidAt: hoursAgo(720),
  },
  {
    handle: "oskar-nowak",
    name: "Oskar Nowak",
    oneLine: "n8n and Make automations for ops-heavy startups.",
    link: "oskarnowak.pl",
    linkKey: "oskarnowak.pl",
    iconUrl: null,
    contactEmail: "oskar@oskarnowak.pl",
    categorySlug: "automation",
    availableFrom: day("2026-08-20"),
    capacity: "1",
    lastValue: 0.003,
    lastPaidAt: hoursAgo(800),
  },
  {
    handle: "leah-mbeki",
    name: "Leah Mbeki",
    oneLine: "Landing pages in Webflow and Framer for seed rounds.",
    link: "leahmbeki.com",
    linkKey: "leahmbeki.com",
    iconUrl: null,
    contactEmail: "leah@leahmbeki.com",
    categorySlug: "landing-pages",
    availableFrom: day("2026-10-01"),
    capacity: "2-3",
    lastValue: 0.002,
    lastPaidAt: hoursAgo(900),
  },
  {
    handle: "theo-lacroix",
    name: "Théo Lacroix",
    oneLine: "React Native and Expo for v1 mobile apps.",
    link: "theolacroix.fr",
    linkKey: "theolacroix.fr",
    iconUrl: null,
    contactEmail: "theo@theolacroix.fr",
    categorySlug: "ios-android",
    availableFrom: day("2026-08-20"),
    capacity: "4-5",
    lastValue: 0.001,
    lastPaidAt: hoursAgo(1000),
  },
  {
    handle: "yuki-tanaka",
    name: "Yuki Tanaka",
    oneLine: "Framer sites with motion for product launches.",
    link: "yukitanaka.design",
    linkKey: "yukitanaka.design",
    iconUrl: null,
    contactEmail: "yuki@yukitanaka.design",
    categorySlug: "framer",
    availableFrom: day("2026-09-05"),
    capacity: "1",
    lastValue: 0.001,
    lastPaidAt: hoursAgo(1100),
  },
];

async function main() {
  for (const row of seed) {
    await prisma.listing.upsert({
      where: { linkKey: row.linkKey },
      create: row,
      update: row,
    });
  }
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
